ERROR - 2023-10-07 03:41:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 03:41:52 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 03:42:28 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 03:42:28 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 03:42:40 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 03:42:40 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 03:43:02 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 03:43:02 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 03:43:41 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 03:43:41 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 03:43:55 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 03:43:55 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
CRITICAL - 2023-10-07 03:59:11 --> "valid_user_email" is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 286.
 1 SYSTEMPATH\Validation\Validation.php(286): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('valid_user_email')
 2 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('user_email', 'user_email', 'admin12@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Register.php(48): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
CRITICAL - 2023-10-07 04:06:08 --> "valid_user_email" is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 286.
 1 SYSTEMPATH\Validation\Validation.php(286): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('valid_user_email')
 2 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('user_email', 'user_email', 'admin12@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Register.php(48): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
CRITICAL - 2023-10-07 04:06:23 --> "valid_user_email" is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 286.
 1 SYSTEMPATH\Validation\Validation.php(286): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('valid_user_email')
 2 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('user_email', 'user_email', 'user@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Register.php(48): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
CRITICAL - 2023-10-07 04:06:35 --> "valid_user_email" is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 286.
 1 SYSTEMPATH\Validation\Validation.php(286): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('valid_user_email')
 2 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('user_email', 'user_email', 'user@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Register.php(48): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
CRITICAL - 2023-10-07 04:07:45 --> "valid_user_email" is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 286.
 1 SYSTEMPATH\Validation\Validation.php(286): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('valid_user_email')
 2 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('user_email', 'user_email', 'user@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Register.php(48): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
CRITICAL - 2023-10-07 04:07:59 --> "valid_user_email" is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 286.
 1 SYSTEMPATH\Validation\Validation.php(286): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('valid_user_email')
 2 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('user_email', 'user_email', 'admin@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Register.php(48): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
CRITICAL - 2023-10-07 04:16:59 --> "valid_user_email" is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 286.
 1 SYSTEMPATH\Validation\Validation.php(286): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('valid_user_email')
 2 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('user_email', 'user_email', 'admin@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Register.php(48): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 04:18:33 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 04:18:33 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 04:19:01 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 04:19:01 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 04:19:24 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 04:19:24 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 04:19:37 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 04:19:37 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 04:21:35 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 04:21:35 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 04:21:55 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 04:21:55 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 04:22:15 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 04:22:15 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
ERROR - 2023-10-07 04:23:24 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6\app\Controllers\Register.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(932): App\Controllers\Register->do_register()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-07 04:23:24 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_name`, `user_email`, `user_password`) VALUES (:user_name:, :user_email:, :user_password:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Register.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->do_register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6\\public\\index.php')
CRITICAL - 2023-10-07 04:48:44 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:48:46 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:48:46 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:49:29 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:49:30 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:49:30 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:49:34 --> Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:32 --> Invalid file: "backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:34 --> Invalid file: "backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:34 --> Invalid file: "backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:34 --> Invalid file: "backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:35 --> Invalid file: "backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:37 --> Invalid file: "backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:37 --> Invalid file: "backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:50 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:51 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:51 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:51 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:51 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:51 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:52 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:52 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:54 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:50:54 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:51:00 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:51:18 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:51:18 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:51:19 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:51:19 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:52:24 --> Invalid file: "/backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('/backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('/backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 04:52:47 --> Invalid file: "backend/pages/register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/pages/register.php')
 2 SYSTEMPATH\Common.php(1180): CodeIgniter\View\View->render('backend/pages/register', [], true)
 3 APPPATH\Controllers\Register.php(12): view('backend/pages/register', [])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 04:54:42 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 04:54:42 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$1Ny1FxgVjN/LQtTWlc4ME.A9/LlYUOUql0LJSrhYj7i9grKbVFU/y\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$1Ny1FxgVjN/LQtTWlc4ME.A9/LlYUOUql0LJSrhYj7i9grKbVFU/y\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$1Ny1FxgVjN/LQtTWlc4ME.A9/LlYUOUql0LJSrhYj7i9grKbVFU/y\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 04:55:22 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 04:55:22 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$ZVQe1kRpOcs3nBomCkIzeusE.FqTeaIm28b8Y1n2w6g1dYGOQG4yC\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$ZVQe1kRpOcs3nBomCkIzeusE.FqTeaIm28b8Y1n2w6g1dYGOQG4yC\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$ZVQe1kRpOcs3nBomCkIzeusE.FqTeaIm28b8Y1n2w6g1dYGOQG4yC\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 04:55:28 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 04:55:28 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$mAsZMJvfkyfHseNQ87Kz/uALB.brbiBVThWyvKPSY6EGOvANpKdxC\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$mAsZMJvfkyfHseNQ87Kz/uALB.brbiBVThWyvKPSY6EGOvANpKdxC\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$mAsZMJvfkyfHseNQ87Kz/uALB.brbiBVThWyvKPSY6EGOvANpKdxC\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 05:06:39 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 05:06:39 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$6EbwOjcuMyxNxXxD.CF74.Rr598jqHOPq5Z8ISZtpC4ChglyKT6xW\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$6EbwOjcuMyxNxXxD.CF74.Rr598jqHOPq5Z8ISZtpC4ChglyKT6xW\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$6EbwOjcuMyxNxXxD.CF74.Rr598jqHOPq5Z8ISZtpC4ChglyKT6xW\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 05:08:05 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 05:08:05 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$ExG6PbaBxFPz6xlEtU2WZe9MqGnBIqQtjTTmbQpA7py5oD6BzBSuu\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$ExG6PbaBxFPz6xlEtU2WZe9MqGnBIqQtjTTmbQpA7py5oD6BzBSuu\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$ExG6PbaBxFPz6xlEtU2WZe9MqGnBIqQtjTTmbQpA7py5oD6BzBSuu\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 05:09:14 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 05:09:14 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$PHrXRQz1crb.APVWmqjHV.of2NzDC97i25243D2f30Ua6Qy.ONmAi\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$PHrXRQz1crb.APVWmqjHV.of2NzDC97i25243D2f30Ua6Qy.ONmAi\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'Bristy\', \'admin@gmail.com\', \'$2y$10$PHrXRQz1crb.APVWmqjHV.of2NzDC97i25243D2f30Ua6Qy.ONmAi\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 05:10:18 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 05:10:18 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$XOlfDuNNu3ZgIyXRi8HGnOLHp8OQ01GPtxl/hYpNeOc2nhikMNRoG\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$XOlfDuNNu3ZgIyXRi8HGnOLHp8OQ01GPtxl/hYpNeOc2nhikMNRoG\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$XOlfDuNNu3ZgIyXRi8HGnOLHp8OQ01GPtxl/hYpNeOc2nhikMNRoG\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 05:11:10 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 05:11:10 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$5wpDLH6tRrELho1bMOf1Be7eJowG9xr37YQz/u/uFC1/s0hOpoUfG\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$5wpDLH6tRrELho1bMOf1Be7eJowG9xr37YQz/u/uFC1/s0hOpoUfG\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$5wpDLH6tRrELho1bMOf1Be7eJowG9xr37YQz/u/uFC1/s0hOpoUfG\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
ERROR - 2023-10-07 05:13:47 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\app\Controllers\Register.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(932): App\Controllers\Register->store()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.6 -blog\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-10-07 05:13:47 --> Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$NhbLwS9e5/mRKWLPfWprfe76QIK75rNR3b9PRjKrC3ZE.pC5rDaUm\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$NhbLwS9e5/mRKWLPfWprfe76QIK75rNR3b9PRjKrC3ZE.pC5rDaUm\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`) VALUES (\'farhana\', \'admin@gmail.com\', \'$2y$10$NhbLwS9e5/mRKWLPfWprfe76QIK75rNR3b9PRjKrC3ZE.pC5rDaUm\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Register->store()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 05:20:59 --> Cannot use object of type stdClass as array
in APPPATH\Controllers\Login.php on line 24.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Login->loginAuth()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
CRITICAL - 2023-10-07 05:22:49 --> Cannot use object of type stdClass as array
in APPPATH\Controllers\Login.php on line 24.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Login->loginAuth()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.6 -blog\\public\\index.php')
